<option value="">- Pilih Kota / Kabupaten -</option>
<option value="1101">Kabupaten Aceh Barat</option>
<option value="1102">Kabupaten Aceh Barat Daya</option>
<option value="1103">Kabupaten Aceh Besar</option>
<option value="1104">Kabupaten Aceh Jaya</option>
<option value="1105">Kabupaten Aceh Nagan Raya</option>
<option value="1106">Kabupaten Aceh Selatan</option>
<option value="1107">Kabupaten Aceh Singkil</option>
<option value="1108">Kabupaten Aceh Tamiang</option>
<option value="1109">Kabupaten Aceh Tengah</option>
<option value="1110">Kabupaten Aceh Tenggara</option>
<option value="1111">Kabupaten Aceh Timur</option>
<option value="1112">Kabupaten Aceh Utara</option>
<option value="1301">Kabupaten Agam</option>
<option value="5301">Kabupaten Alor</option>
<option value="1201">Kabupaten Asahan</option>
<option value="5101">Kabupaten Badung</option>
<option value="6301">Kabupaten Balangan</option>
<option value="3201">Kabupaten Bandung</option>
<option value="7201">Kabupaten Banggai</option>
<option value="7202">Kabupaten Banggai Kepulauan</option>
<option value="1901">Kabupaten Bangka</option>
<option value="1902">Kabupaten Bangka Barat</option>
<option value="1903">Kabupaten Bangka Selatan</option>
<option value="1904">Kabupaten Bangka Tengah</option>
<option value="3501">Kabupaten Bangkalan</option>
<option value="5102">Kabupaten Bangli</option>
<option value="6302">Kabupaten Banjar</option>
<option value="3301">Kabupaten Banjarnegara</option>
<option value="7301">Kabupaten Bantaeng</option>
<option value="3401">Kabupaten Bantul</option>
<option value="1601">Kabupaten Banyuasin</option>
<option value="3302">Kabupaten Banyumas</option>
<option value="3502">Kabupaten Banyuwangi</option>
<option value="6303">Kabupaten Barito Kuala</option>
<option value="6201">Kabupaten Barito Selatan</option>
<option value="6202">Kabupaten Barito Timur</option>
<option value="6203">Kabupaten Barito Utara</option>
<option value="7302">Kabupaten Barru</option>
<option value="3303">Kabupaten Batang</option>
<option value="1501">Kabupaten Batanghari</option>
<option value="3202">Kabupaten Bekasi</option>
<option value="1905">Kabupaten Belitung</option>
<option value="1906">Kabupaten Belitung Timur</option>
<option value="5302">Kabupaten Belu</option>
<option value="1113">Kabupaten Bener Meriah</option>
<option value="1401">Kabupaten Bengkalis</option>
<option value="6101">Kabupaten Bengkayang</option>
<option value="1701">Kabupaten Bengkulu Selatan</option>
<option value="1702">Kabupaten Bengkulu Utara</option>
<option value="6401">Kabupaten Berau</option>
<option value="9101">Kabupaten Biak Numfor</option>
<option value="5201">Kabupaten Bima</option>
<option value="2101">Kabupaten Bintan</option>
<option value="1114">Kabupaten Bireuen</option>
<option value="3503">Kabupaten Blitar</option>
<option value="3304">Kabupaten Blora</option>
<option value="7501">Kabupaten Boalemo</option>
<option value="3203">Kabupaten Bogor</option>
<option value="3504">Kabupaten Bojonegoro</option>
<option value="7101">Kabupaten Bolaang Mongondow</option>
<option value="7102">Kabupaten Bolaang Mongondow Utara</option>
<option value="7401">Kabupaten Bombana</option>
<option value="3505">Kabupaten Bondowoso</option>
<option value="7303">Kabupaten Bone</option>
<option value="7502">Kabupaten Bonebolango</option>
<option value="9102">Kabupaten Boven Digul</option>
<option value="3305">Kabupaten Boyolali</option>
<option value="3306">Kabupaten Brebes</option>
<option value="5103">Kabupaten Buleleng</option>
<option value="7304">Kabupaten Bulukumba</option>
<option value="6402">Kabupaten Bulungan</option>
<option value="1502">Kabupaten Bungo</option>
<option value="7203">Kabupaten Buol</option>
<option value="8101">Kabupaten Buru</option>
<option value="7402">Kabupaten Buton</option>
<option value="7403">Kabupaten Buton Utara</option>
<option value="3204">Kabupaten Ciamis</option>
<option value="3205">Kabupaten Cianjur</option>
<option value="3307">Kabupaten Cilacap</option>
<option value="3206">Kabupaten Cirebon</option>
<option value="1202">Kabupaten Dairi</option>
<option value="1203">Kabupaten Deli Serdang</option>
<option value="3308">Kabupaten Demak</option>
<option value="1302">Kabupaten Dharmasraya</option>
<option value="5202">Kabupaten Dompu</option>
<option value="7204">Kabupaten Donggala</option>
<option value="5303">Kabupaten Ende</option>
<option value="7305">Kabupaten Enrekang</option>
<option value="9201">Kabupaten Fak-Fak</option>
<option value="5304">Kabupaten Flores Timur</option>
<option value="3207">Kabupaten Garut</option>
<option value="1115">Kabupaten Gayo Luas</option>
<option value="5104">Kabupaten Gianyar</option>
<option value="7503">Kabupaten Gorontalo</option>
<option value="7504">Kabupaten Gorontalo Utara</option>
<option value="7306">Kabupaten Gowa</option>
<option value="3506">Kabupaten Gresik</option>
<option value="3309">Kabupaten Grobogan</option>
<option value="3402">Kabupaten Gunung Kidul</option>
<option value="6204">Kabupaten Gunung Mas</option>
<option value="8201">Kabupaten Halmahera Barat</option>
<option value="8202">Kabupaten Halmahera Selatan</option>
<option value="8203">Kabupaten Halmahera Tengah</option>
<option value="8204">Kabupaten Halmahera Timur</option>
<option value="8205">Kabupaten Halmahera Utara</option>
<option value="6304">Kabupaten Hulu Sungai Selatan</option>
<option value="6305">Kabupaten Hulu Sungai Tengah</option>
<option value="6306">Kabupaten Hulu Sungai Utara</option>
<option value="1204">Kabupaten Humbang Hasundutan</option>
<option value="1402">Kabupaten Indragiri Hilir</option>
<option value="1403">Kabupaten Indragiri Hulu</option>
<option value="3208">Kabupaten Indramayu</option>
<option value="9103">Kabupaten Jaya Pura</option>
<option value="9104">Kabupaten Jayawijaya</option>
<option value="3507">Kabupaten Jember</option>
<option value="5105">Kabupaten Jembrana</option>
<option value="7307">Kabupaten Jeneponto</option>
<option value="3310">Kabupaten Jepara</option>
<option value="3508">Kabupaten Jombang</option>
<option value="9202">Kabupaten Kaimana</option>
<option value="1404">Kabupaten Kampar</option>
<option value="6205">Kabupaten Kapuas</option>
<option value="6102">Kabupaten Kapuas Hulu</option>
<option value="5106">Kabupaten Karang Asem</option>
<option value="3311">Kabupaten Karanganyar</option>
<option value="3226">Kabupaten Karawang</option>
<option value="2102">Kabupaten Karimun</option>
<option value="1205">Kabupaten Karo</option>
<option value="6206">Kabupaten Katingan</option>
<option value="1703">Kabupaten Kaur</option>
<option value="6103">Kabupaten Kayong Utara</option>
<option value="3312">Kabupaten Kebumen</option>
<option value="3509">Kabupaten Kediri</option>
<option value="9105">Kabupaten Keerom</option>
<option value="3313">Kabupaten Kendal</option>
<option value="1704">Kabupaten Kepahiang</option>
<option value="7103">Kabupaten Kepl. Talaud</option>
<option value="8102">Kabupaten Kepulauan Aru</option>
<option value="1303">Kabupaten Kepulauan Mentawai</option>
<option value="2103">Kabupaten Kepulauan Riau</option>
<option value="3101">Kabupaten Kepulauan Seribu</option>
<option value="8206">Kabupaten Kepulauan Sula</option>
<option value="3209">Kabupaten Kerawang</option>
<option value="1503">Kabupaten Kerinci</option>
<option value="6104">Kabupaten Ketapang</option>
<option value="3314">Kabupaten Klaten</option>
<option value="5109">Kabupaten Klungkung</option>
<option value="7404">Kabupaten Kolaka</option>
<option value="7405">Kabupaten Kolaka Utara</option>
<option value="7406">Kabupaten Konawe</option>
<option value="7407">Kabupaten Konawe Selatan</option>
<option value="7408">Kabupaten Konawe Utara</option>
<option value="6307">Kabupaten Kotabaru</option>
<option value="6207">Kabupaten Kotawaringin Barat</option>
<option value="6208">Kabupaten Kotawaringin Timur</option>
<option value="1405">Kabupaten Kuantan Singing</option>
<option value="6105">Kabupaten Kubu Raya</option>
<option value="3315">Kabupaten Kudus</option>
<option value="3406">Kabupaten Kulon Progo</option>
<option value="3403">Kabupaten Kulonprogo</option>
<option value="3210">Kabupaten Kuningan</option>
<option value="5305">Kabupaten Kupang</option>
<option value="6403">Kabupaten Kutai Barat</option>
<option value="6404">Kabupaten Kutai Kartanegara</option>
<option value="6405">Kabupaten Kutai Timur</option>
<option value="1206">Kabupaten Labuhan Batu</option>
<option value="1602">Kabupaten Lahat</option>
<option value="6209">Kabupaten Lamandau</option>
<option value="3510">Kabupaten Lamongan</option>
<option value="1801">Kabupaten Lampung Barat</option>
<option value="1802">Kabupaten Lampung Selatan</option>
<option value="1803">Kabupaten Lampung Tengah</option>
<option value="1804">Kabupaten Lampung Timur</option>
<option value="1805">Kabupaten Lampung Utara</option>
<option value="6106">Kabupaten Landak</option>
<option value="1207">Kabupaten Langkat</option>
<option value="3601">Kabupaten Lebak</option>
<option value="1705">Kabupaten Lebong</option>
<option value="5306">Kabupaten Lembata</option>
<option value="1304">Kabupaten Lima Puluh Kota</option>
<option value="2104">Kabupaten Lingga</option>
<option value="5203">Kabupaten Lombok Barat</option>
<option value="5204">Kabupaten Lombok Tengah</option>
<option value="5205">Kabupaten Lombok Timur</option>
<option value="5210">Kabupaten Lombok Utara</option>
<option value="3511">Kabupaten Lumajang</option>
<option value="7308">Kabupaten Luwu</option>
<option value="7309">Kabupaten Luwu Timur</option>
<option value="7310">Kabupaten Luwu Utara</option>
<option value="3512">Kabupaten Madiun</option>
<option value="3316">Kabupaten Magelang</option>
<option value="3513">Kabupaten Magetan</option>
<option value="3211">Kabupaten Majalengka</option>
<option value="7601">Kabupaten Majene</option>
<option value="3514">Kabupaten Malang</option>
<option value="6107">Kabupaten Malawi</option>
<option value="6406">Kabupaten Malinau</option>
<option value="8103">Kabupaten Maluku Tengah</option>
<option value="8104">Kabupaten Maluku Tenggara</option>
<option value="8105">Kabupaten Maluku Tenggara Barat</option>
<option value="7602">Kabupaten Mamasa</option>
<option value="7603">Kabupaten Mamuju</option>
<option value="7604">Kabupaten Mamuju Utara</option>
<option value="1208">Kabupaten Mandailing Natal</option>
<option value="5307">Kabupaten Manggarai</option>
<option value="5308">Kabupaten Manggarai Barat</option>
<option value="9203">Kabupaten Manokwari</option>
<option value="9106">Kabupaten Mappi</option>
<option value="9107">Kabupaten Marauke</option>
<option value="7311">Kabupaten Maros</option>
<option value="1504">Kabupaten Merangin</option>
<option value="9301">Kabupaten Merauke</option>
<option value="1811">Kabupaten Mesuji</option>
<option value="9108">Kabupaten Mimika</option>
<option value="7104">Kabupaten Minahasa</option>
<option value="7105">Kabupaten Minahasa Selatan</option>
<option value="7106">Kabupaten Minahasa Tenggara</option>
<option value="7107">Kabupaten Minahasa Utara</option>
<option value="3515">Kabupaten Mojokerto</option>
<option value="7205">Kabupaten Morowali</option>
<option value="1603">Kabupaten Muara Enim</option>
<option value="1505">Kabupaten Muara Jambi</option>
<option value="1706">Kabupaten Muko-Muko</option>
<option value="7409">Kabupaten Muna</option>
<option value="6210">Kabupaten Murung Raya</option>
<option value="1604">Kabupaten Musi Banyuasin</option>
<option value="1605">Kabupaten Musi Rawas</option>
<option value="9109">Kabupaten Nabire</option>
<option value="5317">Kabupaten Nagekeo</option>
<option value="2105">Kabupaten Natuna</option>
<option value="5309">Kabupaten Ngada</option>
<option value="3516">Kabupaten Nganjuk</option>
<option value="3517">Kabupaten Ngawi</option>
<option value="1209">Kabupaten Nias</option>
<option value="1210">Kabupaten Nias Selatan</option>
<option value="6407">Kabupaten Nunukan</option>
<option value="1606">Kabupaten Ogan Ilir</option>
<option value="1607">Kabupaten Ogan Komering Ilir</option>
<option value="1608">Kabupaten Ogan Komering Ulu</option>
<option value="1609">Kabupaten Oku Selatan</option>
<option value="1610">Kabupaten Oku Timur</option>
<option value="3518">Kabupaten Pacitan</option>
<option value="1228">Kabupaten Padang Lawas</option>
<option value="1211">Kabupaten Padang Lawas Utara</option>
<option value="1305">Kabupaten Padang Pariaman</option>
<option value="1212">Kabupaten Pakpak Bharat</option>
<option value="3519">Kabupaten Pamekasan</option>
<option value="3602">Kabupaten Pandeglang</option>
<option value="3227">Kabupaten Pangandaran</option>
<option value="7312">Kabupaten Pangkajene Kepulauan</option>
<option value="9110">Kabupaten Paniai</option>
<option value="7206">Kabupaten Parigi Muotong</option>
<option value="1306">Kabupaten Pasaman</option>
<option value="1307">Kabupaten Pasaman Barat</option>
<option value="6408">Kabupaten Paser</option>
<option value="3520">Kabupaten Pasuruan</option>
<option value="3317">Kabupaten Pati</option>
<option value="9111">Kabupaten Pegunungan Bintang</option>
<option value="3318">Kabupaten Pekalongan</option>
<option value="1406">Kabupaten Pelalawan</option>
<option value="3319">Kabupaten Pemalang</option>
<option value="6409">Kabupaten Penajam Paser Utara</option>
<option value="1615">Kabupaten Penukal Abab Lematang Ilir</option>
<option value="1308">Kabupaten Pesisir Selatan</option>
<option value="1116">Kabupaten Pidie</option>
<option value="7313">Kabupaten Pinrang</option>
<option value="7505">Kabupaten Pohuwato</option>
<option value="7605">Kabupaten Polewali</option>
<option value="3521">Kabupaten Ponorogo</option>
<option value="6108">Kabupaten Pontianak</option>
<option value="7207">Kabupaten Poso</option>
<option value="3522">Kabupaten Probolinggo</option>
<option value="6211">Kabupaten Pulang Pisau</option>
<option value="8209">Kabupaten Pulau Morotai</option>
<option value="9112">Kabupaten Puncak Jaya</option>
<option value="3320">Kabupaten Purbalingga</option>
<option value="3212">Kabupaten Purwakarta</option>
<option value="3321">Kabupaten Purworejo</option>
<option value="9204">Kabupaten Raja Ampat</option>
<option value="1707">Kabupaten Rejang Lebong</option>
<option value="3322">Kabupaten Rembang</option>
<option value="1407">Kabupaten Rokan Hilir</option>
<option value="1408">Kabupaten Rokan Hulu</option>
<option value="5310">Kabupaten Rote Ndao</option>
<option value="6109">Kabupaten Sambas</option>
<option value="1213">Kabupaten Samosir</option>
<option value="3523">Kabupaten Sampang</option>
<option value="6110">Kabupaten Sanggau</option>
<option value="7108">Kabupaten Sangihe</option>
<option value="9113">Kabupaten Sarmi</option>
<option value="1506">Kabupaten Sarolangun</option>
<option value="7314">Kabupaten Selayar</option>
<option value="1708">Kabupaten Seluma</option>
<option value="3323">Kabupaten Semarang</option>
<option value="8106">Kabupaten Seram Bagian Barat</option>
<option value="8107">Kabupaten Seram Bagian Timur</option>
<option value="3603">Kabupaten Serang</option>
<option value="1214">Kabupaten Serdang Bedagai</option>
<option value="6212">Kabupaten Seruyan</option>
<option value="1409">Kabupaten Siak</option>
<option value="7315">Kabupaten Sidenreng Rappang</option>
<option value="3524">Kabupaten Sidoarjo</option>
<option value="1309">Kabupaten Sijunjung</option>
<option value="5311">Kabupaten Sikka</option>
<option value="1215">Kabupaten Simalungun</option>
<option value="1117">Kabupaten Simeulue</option>
<option value="7316">Kabupaten Sinjai</option>
<option value="6112">Kabupaten Sintang</option>
<option value="3525">Kabupaten Situbondo</option>
<option value="3404">Kabupaten Sleman</option>
<option value="1310">Kabupaten Solok</option>
<option value="1311">Kabupaten Solok Selatan</option>
<option value="7317">Kabupaten Soppeng</option>
<option value="9205">Kabupaten Sorong</option>
<option value="9206">Kabupaten Sorong Selatan</option>
<option value="3324">Kabupaten Sragen</option>
<option value="3213">Kabupaten Subang</option>
<option value="3214">Kabupaten Sukabumi</option>
<option value="6213">Kabupaten Sukamara</option>
<option value="3325">Kabupaten Sukoharjo</option>
<option value="5312">Kabupaten Sumba Barat</option>
<option value="5313">Kabupaten Sumba Timur</option>
<option value="5206">Kabupaten Sumbawa</option>
<option value="5207">Kabupaten Sumbawa Barat</option>
<option value="3215">Kabupaten Sumedang</option>
<option value="3526">Kabupaten Sumenep</option>
<option value="9114">Kabupaten Supiori</option>
<option value="6308">Kabupaten Tabalong</option>
<option value="5107">Kabupaten Tabanan</option>
<option value="7318">Kabupaten Takalar</option>
<option value="6410">Kabupaten Tana Tidung</option>
<option value="7319">Kabupaten Tana Toraja</option>
<option value="6309">Kabupaten Tanah Bumbu</option>
<option value="1312">Kabupaten Tanah Datar</option>
<option value="6310">Kabupaten Tanah Laut</option>
<option value="3604">Kabupaten Tangerang</option>
<option value="1806">Kabupaten Tanggamus</option>
<option value="1507">Kabupaten Tanjung Jabung Barat</option>
<option value="1508">Kabupaten Tanjung Jabung Timur</option>
<option value="1216">Kabupaten Tapanuli Selatan</option>
<option value="1217">Kabupaten Tapanuli Tengah</option>
<option value="1218">Kabupaten Tapanuli Utara</option>
<option value="6311">Kabupaten Tapin</option>
<option value="3216">Kabupaten Tasikmalaya</option>
<option value="1509">Kabupaten Tebo</option>
<option value="3326">Kabupaten Tegal</option>
<option value="9207">Kabupaten Teluk Bintuni</option>
<option value="9208">Kabupaten Teluk Wondama</option>
<option value="3327">Kabupaten Temanggung</option>
<option value="5314">Kabupaten Timor Tengah Selatan</option>
<option value="5315">Kabupaten Timor Tengah Utara</option>
<option value="1219">Kabupaten Toba Samosir</option>
<option value="7208">Kabupaten Tojo Una-Una</option>
<option value="7209">Kabupaten Toli Toli</option>
<option value="9115">Kabupaten Tolikara</option>
<option value="3527">Kabupaten Trenggalek</option>
<option value="3528">Kabupaten Tuban</option>
<option value="1807">Kabupaten Tulang Bawang</option>
<option value="1812">Kabupaten Tulang Bawang Barat</option>
<option value="3529">Kabupaten Tulungagung</option>
<option value="7320">Kabupaten Wajo</option>
<option value="7410">Kabupaten Wakatobi</option>
<option value="9116">Kabupaten Waropen</option>
<option value="1808">Kabupaten Way Kanan</option>
<option value="3328">Kabupaten Wonogiri</option>
<option value="3329">Kabupaten Wonosobo</option>
<option value="9117">Kabupaten Yahukimo</option>
<option value="9118">Kabupaten Yapen Waropen</option>
<option value="1412">Kepulauan Meranti</option>
<option value="8108">Kota Ambon</option>
<option value="6411">Kota Balikpapan</option>
<option value="1118">Kota Banda Aceh</option>
<option value="1809">Kota Bandar Lampung</option>
<option value="3217">Kota Bandung</option>
<option value="3218">Kota Banjar</option>
<option value="6312">Kota Banjarbaru</option>
<option value="6313">Kota Banjarmasin</option>
<option value="2106">Kota Batam</option>
<option value="3530">Kota Batu</option>
<option value="7411">Kota Bau-Bau</option>
<option value="3219">Kota Bekasi</option>
<option value="1709">Kota Bengkulu</option>
<option value="5208">Kota Bima</option>
<option value="1220">Kota Binjai</option>
<option value="7109">Kota Bitung</option>
<option value="3531">Kota Blitar</option>
<option value="3220">Kota Bogor</option>
<option value="6412">Kota Bontang</option>
<option value="1313">Kota Bukittinggi</option>
<option value="3605">Kota Cilegon</option>
<option value="3221">Kota Cimahi</option>
<option value="3222">Kota Cirebon</option>
<option value="5108">Kota Denpasar</option>
<option value="3223">Kota Depok</option>
<option value="1410">Kota Dumai</option>
<option value="7506">Kota Gorontalo</option>
<option value="1227">Kota Gunungsitoli</option>
<option value="3102">Kota Jakarta Barat</option>
<option value="3103">Kota Jakarta Pusat</option>
<option value="3104">Kota Jakarta Selatan</option>
<option value="3105">Kota Jakarta Timur</option>
<option value="3106">Kota Jakarta Utara</option>
<option value="1510">Kota Jambi</option>
<option value="9119">Kota Jayapura</option>
<option value="3532">Kota Kediri</option>
<option value="7412">Kota Kendari</option>
<option value="7110">Kota Kotamobagu</option>
<option value="5316">Kota Kupang</option>
<option value="1119">Kota Langsa</option>
<option value="1120">Kota Lhokseumawe</option>
<option value="1611">Kota Lubuk Linggau</option>
<option value="3533">Kota Madiun</option>
<option value="3330">Kota Magelang</option>
<option value="7321">Kota Makasar</option>
<option value="3534">Kota Malang</option>
<option value="7111">Kota Manado</option>
<option value="5209">Kota Mataram</option>
<option value="1221">Kota Medan</option>
<option value="1810">Kota Metro</option>
<option value="3535">Kota Mojokerto</option>
<option value="1314">Kota Padang</option>
<option value="1315">Kota Padang Panjang</option>
<option value="1222">Kota Padang Sidempuan</option>
<option value="1612">Kota Pagar Alam</option>
<option value="6214">Kota Palangkaraya</option>
<option value="1613">Kota Palembang</option>
<option value="7322">Kota Palopo</option>
<option value="7210">Kota Palu</option>
<option value="1907">Kota Pangkal Pinang</option>
<option value="7323">Kota Pare Pare</option>
<option value="1316">Kota Pariaman</option>
<option value="3536">Kota Pasuruan</option>
<option value="1317">Kota Payakumbuh</option>
<option value="3331">Kota Pekalongan</option>
<option value="1411">Kota Pekanbaru</option>
<option value="1223">Kota Pematang Siantar</option>
<option value="6111">Kota Pontianak</option>
<option value="1614">Kota Prabumulih</option>
<option value="3537">Kota Probolinggo</option>
<option value="1121">Kota Sabang</option>
<option value="3332">Kota Salatiga</option>
<option value="6413">Kota Samarinda</option>
<option value="1318">Kota Sawahlunto</option>
<option value="3333">Kota Semarang</option>
<option value="3607">Kota Serang</option>
<option value="1224">Kota Sibolga</option>
<option value="1319">Kota Solok</option>
<option value="9209">Kota Sorong</option>
<option value="3224">Kota Sukabumi</option>
<option value="3538">Kota Surabaya</option>
<option value="3334">Kota Surakarta</option>
<option value="3606">Kota Tangerang</option>
<option value="3608">Kota Tangerang Selatan</option>
<option value="1225">Kota Tanjung Balai</option>
<option value="2107">Kota Tanjung Pinang</option>
<option value="6414">Kota Tarakan</option>
<option value="3225">Kota Tasikmalaya</option>
<option value="1226">Kota Tebing Tinggi</option>
<option value="3335">Kota Tegal</option>
<option value="8207">Kota Ternate</option>
<option value="8208">Kota Tidore Kepulauan</option>
<option value="7112">Kota Tomohon</option>
<option value="3405">Kota Yogyakarta</option>
<option value="99999">Luar Negeri</option>
<option value="99999">Luar Negeri</option>